sqlite3: fix rare strange exception when table does not exist
Found by running testPruneOrphan many times. Once I even got:

  SystemError: NULL result without error in PyObject_Call