X go/neo: Switch to NEO-kind SHA1
NEO/py sends all zeros for empty data. Without this fix tests fail:

    --- FAIL: TestLoad/py (0.74s)
        xtesting.go:297: load 0285cbacc06d3a4c:0000000000000007: returned err unexpected:
            have: neo://1@127.0.0.1:25910: load 0285cbacc06d3a4c:0000000000000007: data corrupt: checksum mismatch
            want: neo://1@127.0.0.1:25910: load 0285cbacc06d3a4c:0000000000000007: 0000000000000007: object was deleted @0285cbacc06d3a4c
        xtesting.go:297: load 0285cbad858bf2e6:0000000000000006: returned err unexpected:
            have: neo://1@127.0.0.1:25910: load 0285cbad858bf2e6:0000000000000006: data corrupt: checksum mismatch
            want: neo://1@127.0.0.1:25910: load 0285cbad858bf2e6:0000000000000006: 0000000000000006: object was deleted @0285cbad858bf2e6
        xtesting.go:315: load 7fffffffffffffff:0000000000000006: returned err unexpected:
            have: neo://1@127.0.0.1:25910: load 7fffffffffffffff:0000000000000006: data corrupt: checksum mismatch
            want: neo://1@127.0.0.1:25910: load 7fffffffffffffff:0000000000000006: 0000000000000006: object was deleted @0285cbad858bf2e6
        xtesting.go:315: load 7fffffffffffffff:0000000000000007: returned err unexpected:
            have: neo://1@127.0.0.1:25910: load 7fffffffffffffff:0000000000000007: data corrupt: checksum mismatch
            want: neo://1@127.0.0.1:25910: load 7fffffffffffffff:0000000000000007: 0000000000000007: object was deleted @0285cbacc06d3a4c