go/zodb/zeo: Skip handshake/py/msgpack=true on ZEO4
ZEO4 does not have msgpack support and does not take $ZEO_MSGPACK into
account. With ZEO4 this test was failing before:

	--- FAIL: TestHandshake (0.46s)
	    --- FAIL: TestHandshake/py/msgpack=true (0.24s)
	        zeo_test.go:241: handshake: encoding=Z  ; want M

We don't have infrastructure to check python packages versions, so
check it by verifying ZEO.asyncio presence.